name: Build and Release

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write

    steps:
    - uses: actions/checkout@v4

    - uses: oven-sh/setup-bun@v1

    - run: echo "VITE_GOOGLE_CLIENT_ID=${{ secrets.GOOGLE_CLIENT_ID }}" > .env

    - run: bun i && bun run build

    - id: tag
      uses: mathieudutour/github-tag-action@v6.2
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        tag_prefix: ''

    - uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - uses: docker/build-push-action@v5
      env:
        IMAGE: ghcr.io/${{github.repository}}
      with:
        context: .
        push: true
        tags: |
          ${{ env.IMAGE }}:${{ steps.tag.outputs.new_tag }}
          ${{ env.IMAGE }}:latest
